// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseTracker.Api.Services;

namespace PurchaseTracker.Api.Migrations
{
    [DbContext(typeof(BudgetDb))]
    partial class BudgetDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PurchaseTracker.Api.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Housing"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Transportation"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Food"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Utilities"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Medical & Healthcare"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Saving, Investing, & Debt Payments"
                        });
                });

            modelBuilder.Entity("PurchaseTracker.Api.Models.PurchaseModel", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeName")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = 1,
                            CategoryId = 4,
                            Memo = "Less than last month. Yay!",
                            PayeeName = "Electricity Company",
                            PurchaseAmount = 99.99m,
                            PurchaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2,
                            CategoryId = 3,
                            Memo = "Tacos!",
                            PayeeName = "Fuzzies!",
                            PurchaseAmount = 99.99m,
                            PurchaseDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 3,
                            CategoryId = 1,
                            Memo = "Rent.",
                            PayeeName = "Property Mangement Company",
                            PurchaseAmount = 1200.00m,
                            PurchaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 4,
                            CategoryId = 5,
                            Memo = "Kid doctor appointment.",
                            PayeeName = "Mercy Hostpital",
                            PurchaseAmount = 99.99m,
                            PurchaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PurchaseTracker.Api.Models.PurchaseModel", b =>
                {
                    b.HasOne("PurchaseTracker.Api.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
